### ISSUE TITLE
Vapor template docker-compose.yml crashes docker compose with mysterious go errors

### ISSUE THREAD

**Issue by jaanus** [vapor/template#50]
### Describe the bug

Vapor template `docker-compose.yml` contains directives that cause `docker compose` to crash with a mysterious error.

### To Reproduce

`vapor new template-app` to create an app from template. Use Fluent with Postgres, no Leaf.

`cd template-app`

`docker compose up`

After building, Docker crashes with some mysterious Go errors.

<img width="1178" alt="Screenshot 2021-07-16 at 16 23 57" src="https://user-images.githubusercontent.com/184253/125954997-2d639c92-e904-4c2e-8f42-56bef3d3c143.png">

### Expected behavior

`docker compose up` should build and run the containers.

### Environment

* macOS Big Sur 11.4 (20F71)
* Docker Desktop for Mac 3.5.2 (66501)
* Vapor Framework version: 4.48.2
* Vapor Toolbox version: 18.3.3

### Additional context

The issue is caused by this piece of `revert` and `migrate` targets configuration in `docker-compose.yml`:

```
deploy:
      replicas: 0
```

When I comment these lines out, the containers do build and run, but I see blank non-running `revert` and `migrate` containers in my Docker Dashboard, which probably shouldn’t be like that.

**Comment by 0xTim** [comment]
@jaanus which architecture are you trying to run on? Intel or M1?

**Comment by jaanus** [comment]
This is all on Intel.

**Comment by bartjacobs** [comment]
I'm running into a similar issue using the latest version of Vapor (4.48.3) and Docker (3.5.2). I created a Vapor application using the Vapor toolbox, adding support for Fluent. When I run `docker-compose build`, the following error is thrown.

```shell
docker-compose build
db uses an image, skipping
Building revert
invalid argument ":latest" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
ERROR: Service 'revert' failed to build : Build failed
```

This is what **docker-compose.yml** looks like:

```yaml
# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#      Start app: docker-compose up app
# Start database: docker-compose up db
# Run migrations: docker-compose run migrate
#       Stop all: docker-compose down (add -v to wipe db)
#
version: '3.7'

volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_NAME: vapor_database
  DATABASE_USERNAME: vapor_username
  DATABASE_PASSWORD: vapor_password

services:
  app:
    image: :latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    image: :latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: :latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  db:
    image: postgres:12-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD: vapor_password
      POSTGRES_DB: vapor_database
    ports:
      - '5432:5432'
```
